"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
async function ctx(){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");return{context,orgId:context.membership.organization_id as string,supabase:await createClient()}}
export async function addContactTag(formData:FormData){const contactId=z.string().uuid().parse(formData.get("contact_id"));const tagId=z.string().uuid().parse(formData.get("tag_id"));const{orgId,supabase}=await ctx();const{error}=await supabase.from("contact_tags").upsert({organization_id:orgId,contact_id:contactId,tag_id:tagId});if(error)throw new Error(error.message);revalidatePath(`/contacts/${contactId}`)}
export async function removeContactTag(formData:FormData){const contactId=z.string().uuid().parse(formData.get("contact_id"));const tagId=z.string().uuid().parse(formData.get("tag_id"));const{orgId,supabase}=await ctx();const{error}=await supabase.from("contact_tags").delete().eq("organization_id",orgId).eq("contact_id",contactId).eq("tag_id",tagId);if(error)throw new Error(error.message);revalidatePath(`/contacts/${contactId}`)}
export async function addContactToList(formData:FormData){const contactId=z.string().uuid().parse(formData.get("contact_id"));const listId=z.string().uuid().parse(formData.get("list_id"));const{orgId,supabase}=await ctx();const{error}=await supabase.from("contact_list_members").upsert({organization_id:orgId,contact_id:contactId,list_id:listId});if(error)throw new Error(error.message);revalidatePath(`/contacts/${contactId}`)}
export async function removeContactFromList(formData:FormData){const contactId=z.string().uuid().parse(formData.get("contact_id"));const listId=z.string().uuid().parse(formData.get("list_id"));const{orgId,supabase}=await ctx();const{error}=await supabase.from("contact_list_members").delete().eq("organization_id",orgId).eq("contact_id",contactId).eq("list_id",listId);if(error)throw new Error(error.message);revalidatePath(`/contacts/${contactId}`)}
export async function updateContactConsent(formData:FormData){const contactId=z.string().uuid().parse(formData.get("contact_id"));const{context,orgId,supabase}=await ctx();const payload={email_consent:formData.get("email_consent")==="on",sms_consent:formData.get("sms_consent")==="on",whatsapp_consent:formData.get("whatsapp_consent")==="on"};const{error}=await supabase.from("contacts").update(payload).eq("organization_id",orgId).eq("id",contactId);if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({organization_id:orgId,user_id:context.user.id,action:"contact.consent.update",entity_type:"contact",entity_id:contactId,category:"activity",severity:"notice",after_data:payload});revalidatePath(`/contacts/${contactId}`)}
