import { createHash } from "crypto";
import { NextRequest,NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { constantTimeTokenEquals } from "@/lib/security/webhooks";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { findContactByPhone,recordProviderEvent } from "@/lib/channels/events";
export async function POST(req:NextRequest,{params}:{params:Promise<{provider:string;integrationKey:string}>}){
 const{provider,integrationKey}=await params;const admin=createAdminClient();const{data:i}=await admin.from("integrations").select("id,organization_id").eq("webhook_path_key",integrationKey).eq("provider",provider).eq("channel","sms").eq("status","connected").maybeSingle();if(!i)return NextResponse.json({error:"Not found"},{status:404});
 const supplied=req.headers.get("x-campaign-webhook-secret")||req.nextUrl.searchParams.get("secret");if(!constantTimeTokenEquals(supplied,process.env.WEBHOOK_SECRET))return NextResponse.json({error:"Unauthorized"},{status:401});try{await enforceRateLimit(`sms-webhook:${integrationKey}`,180,60);}catch{return NextResponse.json({error:"Rate limit exceeded"},{status:429});}
 const raw=await req.text();const key=createHash("sha256").update(raw).digest("hex");const{error:dup}=await admin.from("webhook_receipts").insert({integration_id:i.id,provider,event_key:key});if(dup?.code==="23505")return NextResponse.json({ok:true,replay:true});let body:any;try{body=JSON.parse(raw);}catch{return NextResponse.json({error:"Invalid JSON"},{status:400});}
 const items=Array.isArray(body)?body:[body];let recorded=0;for(const x of items){const eventRaw=String(x.event||x.type||x.direction||"").toLowerCase();const isInbound=eventRaw.includes("incoming")||eventRaw==="inbound";if(isInbound){const from=String(x.from||x.phone_number||x.sender||"").replace(/\D/g,"");const text=String(x.text||x.message||x.sms||"");if(from){const contact=await findContactByPhone(i.organization_id,from);const inboundId=String(x.message_id||x.messageId||x.id||crypto.randomUUID());await admin.from("inbound_messages").upsert({organization_id:i.organization_id,contact_id:contact?.id||null,channel:"sms",provider,provider_message_id:inboundId,sender:from,recipient:x.to||null,message_type:"text",body:text,raw_payload:x},{onConflict:"provider,provider_message_id",ignoreDuplicates:true});if(contact?.id){await admin.from("communication_history").insert({organization_id:i.organization_id,contact_id:contact.id,channel:"sms",direction:"inbound",status:"received",destination:from,provider,provider_message_id:inboundId,metadata:{body:text}});if(["stop","unsubscribe","cancel","quit"].includes(text.trim().toLowerCase())){await admin.from("contacts").update({sms_consent:false}).eq("id",contact.id);await admin.from("suppression_entries").upsert({organization_id:i.organization_id,contact_id:contact.id,channel:"sms",destination:from,reason:"unsubscribe",source:"sms_inbound"},{onConflict:"organization_id,channel,destination"});}}await admin.from("message_events").insert({organization_id:i.organization_id,channel:"sms",provider,provider_message_id:inboundId,event_type:"received",metadata:{from}});recorded++;}continue;}
  const messageId=String(x.message_id||x.messageId||x.id||x.request_id||"");const status=String(x.status||x.delivery_status||x.event||"").toLowerCase();const eventType=status.includes("undeliver")?"undelivered":status.includes("deliver")?"delivered":status.includes("fail")||status.includes("reject")?"failed":status.includes("sent")?"sent":"accepted";if(!messageId)continue;await recordProviderEvent({organizationId:i.organization_id,channel:"sms",provider,providerMessageId:messageId,eventType,metadata:x,destination:x.to||x.phone_number||null});recorded++;}
 return NextResponse.json({ok:true,recorded});
}
