import { createClient } from "@/lib/supabase/server";
import { getCurrentContext } from "@/lib/auth/context";
import { createCampaign } from "../actions";
export default async function NewCampaignPage(){
  const ctx=await getCurrentContext();const orgId=ctx?.membership?.organization_id as string;const supabase=await createClient();
  const[listsQ,segmentsQ,emailTemplatesQ,channelTemplatesQ,orgQ]=await Promise.all([
    supabase.from("contact_lists").select("id,name").eq("organization_id",orgId),supabase.from("segments").select("id,name,cached_count").eq("organization_id",orgId),
    supabase.from("email_templates").select("id,name,subject").eq("organization_id",orgId).eq("status","active"),supabase.from("channel_templates").select("id,name,channel,provider_template_name").eq("organization_id",orgId).eq("status","active"),supabase.from("organizations").select("timezone").eq("id",orgId).single()
  ]);
  return <div className="mx-auto max-w-4xl space-y-6"><div><p className="eyebrow">Multi-channel campaigns</p><h2 className="mt-1 text-3xl font-semibold">Create campaign</h2><p className="mt-2 text-sm text-slate-500">Email, SMS and WhatsApp share the same audience, approval, queue and tracking foundation.</p></div><form action={createCampaign} className="panel grid gap-5 p-6 md:grid-cols-2">
    <label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">Campaign name</span><input required name="name" className="field" placeholder="October customer reactivation"/></label>
    <label className="space-y-2"><span className="text-sm font-semibold">Channel</span><select name="channel" className="field"><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select><p className="text-xs text-slate-500">Fill the fields relevant to the channel you choose.</p></label>
    <label className="space-y-2"><span className="text-sm font-semibold">Timezone</span><input required name="timezone" className="field" defaultValue={orgQ.data?.timezone||"Africa/Lagos"}/></label>
    <div className="md:col-span-2 rounded-2xl border border-slate-200 p-4"><p className="text-sm font-bold">Email-only fields</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">Subject</span><input name="subject" className="field" placeholder={'Welcome back, {{first_name | default:"Customer"}}'}/></label><label className="space-y-2"><span className="text-sm font-semibold">Sender name</span><input name="sender_name" className="field"/></label><label className="space-y-2"><span className="text-sm font-semibold">Sender email</span><input type="email" name="sender_email" className="field"/></label><label className="space-y-2"><span className="text-sm font-semibold">Reply-to</span><input type="email" name="reply_to" className="field"/></label><label className="space-y-2"><span className="text-sm font-semibold">Email template</span><select name="template_id" className="field"><option value="">Select template</option>{(emailTemplatesQ.data||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></div>
    <div className="md:col-span-2 rounded-2xl border border-slate-200 p-4"><p className="text-sm font-bold">SMS / WhatsApp template</p><label className="mt-4 block space-y-2"><span className="text-sm font-semibold">Channel template</span><select name="channel_template_id" className="field"><option value="">Select SMS or WhatsApp template</option>{(channelTemplatesQ.data||[]).map((x:any)=><option key={x.id} value={x.id}>{x.channel.toUpperCase()} · {x.name}{x.provider_template_name?` · ${x.provider_template_name}`:""}</option>)}</select></label></div>
    <label className="space-y-2"><span className="text-sm font-semibold">Audience type</span><select name="audience_type" className="field"><option value="list">Static list</option><option value="segment">Dynamic segment</option></select></label><div/>
    <label className="space-y-2"><span className="text-sm font-semibold">List</span><select name="list_id" className="field"><option value="">Select list</option>{(listsQ.data||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label className="space-y-2"><span className="text-sm font-semibold">Segment</span><select name="segment_id" className="field"><option value="">Select segment</option>{(segmentsQ.data||[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.cached_count||0})</option>)}</select></label>
    <div className="md:col-span-2 flex justify-end"><button className="btn-primary">Create draft campaign</button></div>
  </form></div>;
}
