"use server";
import { z } from "zod";
import { redirect } from "next/navigation";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { materializeCampaign } from "@/lib/campaigns/materialize";
import { recordAudit } from "@/lib/audit";

const createSchema=z.object({
  name:z.string().min(2).max(140), channel:z.enum(["email","sms","whatsapp"]),
  subject:z.string().max(220).optional().default(""), sender_name:z.string().max(120).optional().default(""), sender_email:z.string().optional().default(""), reply_to:z.string().optional().default(""),
  audience_type:z.enum(["list","segment"]), list_id:z.string().uuid().or(z.literal("")), segment_id:z.string().uuid().or(z.literal("")),
  template_id:z.string().uuid().or(z.literal("")), channel_template_id:z.string().uuid().or(z.literal("")), timezone:z.string().min(1).max(80)
});
export async function createCampaign(formData:FormData){
  const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");
  const parsed=createSchema.parse(Object.fromEntries(formData));const supabase=await createClient();const orgId=context.membership.organization_id as string;
  if(parsed.audience_type==="list"&&!parsed.list_id)throw new Error("Select a contact list.");if(parsed.audience_type==="segment"&&!parsed.segment_id)throw new Error("Select a segment.");
  let content:unknown[]=[];let textContent:string|null=null;let emailTemplateId:string|null=null;let channelTemplateId:string|null=null;
  if(parsed.channel==="email"){
    if(!parsed.template_id||!parsed.subject||!parsed.sender_name||!z.string().email().safeParse(parsed.sender_email).success)throw new Error("Email campaigns require a template, subject, sender name and valid sender email.");
    const{data:template,error}=await supabase.from("email_templates").select("content").eq("organization_id",orgId).eq("id",parsed.template_id).single();if(error)throw error;content=template.content||[];emailTemplateId=parsed.template_id;
  }else{
    if(!parsed.channel_template_id)throw new Error(`${parsed.channel} campaigns require a channel template.`);
    const{data:template,error}=await supabase.from("channel_templates").select("body,channel").eq("organization_id",orgId).eq("id",parsed.channel_template_id).eq("channel",parsed.channel).single();if(error)throw error;textContent=template.body;channelTemplateId=parsed.channel_template_id;
  }
  const{data,error}=await supabase.from("campaigns").insert({organization_id:orgId,created_by:context.user.id,name:parsed.name,channel:parsed.channel,subject:parsed.channel==="email"?parsed.subject:null,sender_name:parsed.channel==="email"?parsed.sender_name:null,sender_email:parsed.channel==="email"?parsed.sender_email:null,reply_to:parsed.channel==="email"?(parsed.reply_to||null):null,audience_type:parsed.audience_type,list_id:parsed.audience_type==="list"?parsed.list_id:null,segment_id:parsed.audience_type==="segment"?parsed.segment_id:null,template_id:emailTemplateId,channel_template_id:channelTemplateId,content,text_content:textContent,timezone:parsed.timezone,status:"draft"}).select("id").single();
  if(error)throw error;await recordAudit({organizationId:orgId,userId:context.user.id,action:"campaign.create",entityType:"campaign",entityId:data.id,category:"campaign",afterData:{name:parsed.name,channel:parsed.channel,audience_type:parsed.audience_type}});redirect(`/campaigns/${data.id}`);
}
export async function scheduleCampaign(formData:FormData){
  const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");
  const campaignId=z.string().uuid().parse(formData.get("campaign_id"));const when=z.string().min(1).parse(formData.get("scheduled_at"));const provider=z.string().min(2).max(60).parse(formData.get("provider"));
  const supabase=await createClient();const orgId=context.membership.organization_id as string;
  const{data:campaign}=await supabase.from("campaigns").select("status,channel").eq("organization_id",orgId).eq("id",campaignId).single();if(!campaign||campaign.status!=="approved")throw new Error("Campaign must be approved before it can be scheduled.");
  const{data:canSend}=await supabase.rpc("has_permission",{p_org:orgId,p_permission:"campaigns.send"});if(!canSend)throw new Error("You do not have permission to send campaigns.");
  const{data:integration,error}=await supabase.from("integrations").select("daily_limit,status").eq("organization_id",orgId).eq("provider",provider).eq("channel",campaign.channel).single();if(error||integration.status!=="connected")throw new Error(`Selected ${campaign.channel} provider is not connected.`);
  const result=await materializeCampaign(campaignId,orgId,provider,new Date(when).toISOString(),integration.daily_limit||300,50);
  await recordAudit({organizationId:orgId,userId:context.user.id,action:"campaign.schedule",entityType:"campaign",entityId:campaignId,category:"campaign",severity:"notice",afterData:{scheduled_at:when,provider,channel:campaign.channel,recipients:result.recipients,days:result.days}});redirect(`/campaigns/${campaignId}`);
}
export async function submitCampaign(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const campaignId=z.string().uuid().parse(formData.get("campaign_id"));const supabase=await createClient();const orgId=context.membership.organization_id as string;const{error}=await supabase.from("campaigns").update({status:"pending_approval",submitted_by:context.user.id,submitted_at:new Date().toISOString(),rejection_reason:null,rejected_by:null,rejected_at:null}).eq("organization_id",orgId).eq("id",campaignId).eq("status","draft");if(error)throw new Error(error.message);await supabase.from("campaign_approval_events").insert({organization_id:orgId,campaign_id:campaignId,action:"submitted",actor_id:context.user.id});await recordAudit({organizationId:orgId,userId:context.user.id,action:"campaign.submit",entityType:"campaign",entityId:campaignId,category:"campaign"});redirect(`/campaigns/${campaignId}`);}
export async function approveCampaign(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const campaignId=z.string().uuid().parse(formData.get("campaign_id"));const supabase=await createClient();const orgId=context.membership.organization_id as string;const{data:allowed}=await supabase.rpc("has_permission",{p_org:orgId,p_permission:"campaigns.approve"});if(!allowed)throw new Error("You do not have permission to approve campaigns.");const{error}=await supabase.from("campaigns").update({status:"approved",approved_by:context.user.id,approved_at:new Date().toISOString(),rejected_by:null,rejected_at:null,rejection_reason:null}).eq("organization_id",orgId).eq("id",campaignId).eq("status","pending_approval");if(error)throw new Error(error.message);await supabase.from("campaign_approval_events").insert({organization_id:orgId,campaign_id:campaignId,action:"approved",actor_id:context.user.id});await recordAudit({organizationId:orgId,userId:context.user.id,action:"campaign.approve",entityType:"campaign",entityId:campaignId,category:"campaign",severity:"notice"});redirect(`/campaigns/${campaignId}`);}
export async function rejectCampaign(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const campaignId=z.string().uuid().parse(formData.get("campaign_id"));const note=z.string().min(3).max(500).parse(formData.get("reason"));const supabase=await createClient();const orgId=context.membership.organization_id as string;const{data:allowed}=await supabase.rpc("has_permission",{p_org:orgId,p_permission:"campaigns.approve"});if(!allowed)throw new Error("You do not have permission to reject campaigns.");const{error}=await supabase.from("campaigns").update({status:"draft",rejected_by:context.user.id,rejected_at:new Date().toISOString(),rejection_reason:note}).eq("organization_id",orgId).eq("id",campaignId).eq("status","pending_approval");if(error)throw new Error(error.message);await supabase.from("campaign_approval_events").insert({organization_id:orgId,campaign_id:campaignId,action:"rejected",actor_id:context.user.id,note});await recordAudit({organizationId:orgId,userId:context.user.id,action:"campaign.reject",entityType:"campaign",entityId:campaignId,category:"campaign",severity:"warning",afterData:{reason:note}});redirect(`/campaigns/${campaignId}`);}
