import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getCurrentContext } from "@/lib/auth/context";

export default async function AuditPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const q=await searchParams;const ctx=await getCurrentContext();const orgId=ctx?.membership?.organization_id as string;const supabase=await createClient();
 let query=supabase.from("audit_logs").select("id,action,entity_type,entity_id,category,severity,source,actor_email,ip_address,user_agent,created_at,metadata",{count:"exact"}).eq("organization_id",orgId).order("created_at",{ascending:false});
 if(q.action)query=query.ilike("action",`%${q.action}%`);if(q.category)query=query.eq("category",q.category);if(q.severity)query=query.eq("severity",q.severity);if(q.actor)query=query.ilike("actor_email",`%${q.actor}%`);if(q.from)query=query.gte("created_at",new Date(`${q.from}T00:00:00`).toISOString());if(q.to)query=query.lte("created_at",new Date(`${q.to}T23:59:59`).toISOString());
 const page=Math.max(1,Number(q.page||1)||1);const pageSize=50;query=query.range((page-1)*pageSize,page*pageSize-1);const{data=[],count=0}=await query;
 const params=new URLSearchParams();for(const[k,v]of Object.entries(q))if(v&&k!=="page")params.set(k,v);
 return <div className="mx-auto max-w-[1500px] space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Phase 16 · Governance</p><h2 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Audit & activity monitoring</h2><p className="mt-2 text-sm text-slate-500">Search immutable organization activity by actor, category, severity and date.</p></div><Link href={`/api/audit/export?${params.toString()}`} className="btn-secondary">Export CSV</Link></div>
 <form className="panel grid gap-3 p-4 md:grid-cols-6"><input name="action" className="field" placeholder="Action contains…" defaultValue={q.action||""}/><input name="actor" className="field" placeholder="Actor email…" defaultValue={q.actor||""}/><select name="category" className="field" defaultValue={q.category||""}><option value="">All categories</option><option value="activity">Activity</option><option value="campaign">Campaign</option><option value="integration">Integration</option><option value="security">Security</option><option value="team">Team</option></select><select name="severity" className="field" defaultValue={q.severity||""}><option value="">All severity</option><option value="info">Info</option><option value="notice">Notice</option><option value="warning">Warning</option><option value="critical">Critical</option></select><input name="from" type="date" className="field" defaultValue={q.from||""}/><div className="flex gap-2"><input name="to" type="date" className="field" defaultValue={q.to||""}/><button className="btn-primary">Filter</button></div></form>
 <div className="panel overflow-hidden"><div className="hidden grid-cols-[1.2fr_.8fr_.8fr_1fr_1fr] border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500 md:grid"><span>Action</span><span>Actor</span><span>Category</span><span>Entity</span><span>Time</span></div>{data.length===0?<div className="p-10 text-center text-sm text-slate-500">No audit events match these filters.</div>:data.map((x:any)=><div key={x.id} className="grid gap-2 border-b px-5 py-4 text-sm last:border-0 md:grid-cols-[1.2fr_.8fr_.8fr_1fr_1fr]"><div><p className="font-semibold">{x.action}</p><p className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${x.severity==="critical"?"bg-rose-100 text-rose-700":x.severity==="warning"?"bg-amber-100 text-amber-700":"bg-slate-100 text-slate-600"}`}>{x.severity}</p></div><span className="break-all text-slate-500">{x.actor_email||"System"}</span><span className="capitalize text-slate-500">{x.category}</span><span className="text-slate-500">{x.entity_type||"—"}{x.entity_id?` · ${x.entity_id.slice(0,8)}`:""}</span><span className="text-slate-500">{new Date(x.created_at).toLocaleString()}</span></div>)}</div>
 <div className="flex items-center justify-between text-sm text-slate-500"><span>{count||0} events</span><div className="flex gap-2">{page>1&&<Link className="btn-secondary" href={`/audit?${new URLSearchParams({...Object.fromEntries(params),page:String(page-1)}).toString()}`}>Previous</Link>}{page*pageSize<(count||0)&&<Link className="btn-secondary" href={`/audit?${new URLSearchParams({...Object.fromEntries(params),page:String(page+1)}).toString()}`}>Next</Link>}</div></div>
 </div>;
}
