"use client";
import { useState } from "react";
import { Plus, Trash2, Loader2 } from "lucide-react";
import { createSegment } from "@/app/(dashboard)/contacts/segments/actions";

type Rule={field:string;operator:string;value:string};
const fields=[["branch","Branch"],["customer_type","Customer Type"],["customer_status","Customer Status"],["account_type","Account Type"],["relationship_manager","Relationship Manager"],["country","Country"],["state","State"],["city","City"],["date_joined","Date Joined"],["last_transaction_date","Last Transaction Date"],["balance_band","Balance Band"],["email","Email"],["phone","Phone"]];
const operators=[["equals","Equals"],["not_equals","Does not equal"],["contains","Contains"],["does_not_contain","Does not contain"],["before","Before"],["after","After"],["is_empty","Is empty"],["is_not_empty","Is not empty"],["in","Is one of"],["not_in","Is not one of"]];
export function SegmentBuilder(){const [name,setName]=useState("");const [join,setJoin]=useState<"and"|"or">("and");const [rules,setRules]=useState<Rule[]>([{field:"branch",operator:"equals",value:""}]);const [preview,setPreview]=useState<{count:number;sample:Array<{id:string;full_name:string|null;email:string|null;branch:string|null}>;limited:boolean}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const update=(i:number,key:keyof Rule,value:string)=>setRules(r=>r.map((x,n)=>n===i?{...x,[key]:value}:x));
async function runPreview(){setBusy(true);setError("");try{const res=await fetch("/api/segments/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operator:join,children:rules})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Preview failed");setPreview(data)}catch(e){setError(e instanceof Error?e.message:"Preview failed")}finally{setBusy(false)}}
return <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="panel p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Segment builder</h2><p className="mt-1 text-sm text-slate-500">Build dynamic audiences from contact attributes.</p></div><input className="field max-w-xs" value={name} onChange={e=>setName(e.target.value)} placeholder="Segment name"/></div><div className="mt-6 flex items-center gap-3 text-sm"><span className="font-medium">Match</span><select className="field w-auto" value={join} onChange={e=>setJoin(e.target.value as "and"|"or")}><option value="and">ALL rules (AND)</option><option value="or">ANY rule (OR)</option></select></div><div className="mt-4 space-y-3">{rules.map((rule,i)=><div key={i} className="grid gap-2 rounded-xl border border-slate-200 p-3 md:grid-cols-[1fr_1fr_1.2fr_auto]"><select className="field" value={rule.field} onChange={e=>update(i,"field",e.target.value)}>{fields.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select className="field" value={rule.operator} onChange={e=>update(i,"operator",e.target.value)}>{operators.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input className="field" value={rule.value} disabled={["is_empty","is_not_empty"].includes(rule.operator)} onChange={e=>update(i,"value",e.target.value)} placeholder={rule.operator==="in"?"Value 1, Value 2":"Value"}/><button className="btn-secondary px-3" disabled={rules.length===1} onClick={()=>setRules(r=>r.filter((_,n)=>n!==i))}><Trash2 className="size-4"/></button></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setRules(r=>[...r,{field:"branch",operator:"equals",value:""}])}><Plus className="size-4"/>Add rule</button><button className="btn-primary" disabled={busy} onClick={()=>void runPreview()}>{busy?<Loader2 className="size-4 animate-spin"/>:null}Preview audience</button></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</div>
<div className="panel overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">Audience preview</h2></div>{preview?<><div className="p-5"><div className="text-4xl font-bold tracking-tight">{preview.count}</div><div className="mt-1 text-sm text-slate-500">matching contacts{preview.limited?" within the first 5,000 records":""}</div></div><div className="divide-y divide-slate-100 border-t border-slate-100">{preview.sample.map(c=><div key={c.id} className="p-4"><div className="font-medium">{c.full_name||"Unnamed contact"}</div><div className="text-xs text-slate-500">{c.email||"No email"}{c.branch?` · ${c.branch}`:""}</div></div>)}</div><form action={createSegment} className="border-t border-slate-200 p-5"><input type="hidden" name="name" value={name}/><input type="hidden" name="rules" value={JSON.stringify({operator:join,children:rules})}/><input type="hidden" name="cached_count" value={preview.count}/><button className="btn-primary w-full" disabled={!name.trim()}>Save segment</button></form></>:<div className="p-10 text-center text-sm text-slate-500">Add your rules and preview the audience before saving.</div>}</div></div>}
