import { createHash } from "crypto";
import { NextRequest,NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { constantTimeTokenEquals } from "@/lib/security/webhooks";
import { recordProviderEvent } from "@/lib/channels/events";
export const runtime="nodejs";
type Normalized={messageId?:string;type?:string;timestamp?:string;metadata?:Record<string,unknown>};
function normalize(provider:string,body:any):Normalized{if(provider==="brevo")return{messageId:body["message-id"]||body.messageId,type:body.event,timestamp:body.date,metadata:body};if(provider==="resend")return{messageId:body.data?.email_id||body.data?.id,type:String(body.type||"").split(".").pop(),timestamp:body.created_at,metadata:body};if(provider==="mailjet")return{messageId:String(body.MessageID||body.Message_GUID||""),type:body.event,timestamp:body.time?new Date(Number(body.time)*1000).toISOString():undefined,metadata:body};return{};}
const map:Record<string,string>={request:"sent",sent:"sent",delivered:"delivered",opened:"opened",open:"opened",clicked:"clicked",click:"clicked",bounce:"bounced",bounced:"bounced",blocked:"failed",error:"failed",failed:"failed",spam:"complained",complained:"complained",unsub:"unsubscribed",unsubscribed:"unsubscribed"};
export async function POST(request:NextRequest,{params}:{params:Promise<{provider:string}>}){const{provider}=await params;const supplied=request.headers.get("x-campaign-webhook-secret")||request.nextUrl.searchParams.get("secret");if(!constantTimeTokenEquals(supplied,process.env.WEBHOOK_SECRET))return NextResponse.json({error:"Unauthorized"},{status:401});try{await enforceRateLimit(`email-webhook:${provider}`,300,60);}catch{return NextResponse.json({error:"Rate limit exceeded"},{status:429});}const rawText=await request.text();let raw:any;try{raw=JSON.parse(rawText);}catch{return NextResponse.json({error:"Invalid JSON"},{status:400});}const items=Array.isArray(raw)?raw:[raw];const admin=createAdminClient();let recorded=0;for(const item of items){const n=normalize(provider,item);const eventType=map[String(n.type||"").toLowerCase()];if(!n.messageId||!eventType)continue;let{data:r}=await admin.from("campaign_recipients").select("id,organization_id,campaign_id,contact_id,email").eq("provider_message_id",n.messageId).maybeSingle();let orgId=r?.organization_id as string|undefined;if(!orgId){const{data:e}=await admin.from("message_events").select("organization_id").eq("provider_message_id",n.messageId).order("id",{ascending:true}).limit(1).maybeSingle();orgId=e?.organization_id;}if(!orgId)continue;const{data:intg}=await admin.from("integrations").select("id").eq("organization_id",orgId).eq("provider",provider).eq("channel","email").limit(1).maybeSingle();const key=createHash("sha256").update(`${n.messageId}:${eventType}:${n.timestamp||""}:${rawText.slice(0,2000)}`).digest("hex");if(intg?.id){const{error:dup}=await admin.from("webhook_receipts").insert({integration_id:intg.id,provider,event_key:key});if(dup?.code==="23505")continue;}await recordProviderEvent({organizationId:orgId,channel:"email",provider,providerMessageId:n.messageId,eventType,metadata:n.metadata||{}});if(r?.email&&["bounced","complained","unsubscribed"].includes(eventType)){const reason=eventType==="bounced"?"hard_bounce":eventType==="complained"?"complaint":"unsubscribe";await admin.from("suppression_entries").upsert({organization_id:orgId,contact_id:r.contact_id,channel:"email",destination:String(r.email).toLowerCase(),reason,source:`${provider}_webhook`,campaign_id:r.campaign_id},{onConflict:"organization_id,channel,destination"});if(eventType==="unsubscribed"&&r.contact_id)await admin.from("contacts").update({email_consent:false}).eq("id",r.contact_id);}recorded++;}return NextResponse.json({ok:true,recorded});}
