import { createHash } from "crypto";
import { NextRequest,NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptSecret } from "@/lib/security/secrets";
import { verifyMetaSignature,constantTimeTokenEquals } from "@/lib/security/webhooks";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { findContactByPhone,recordProviderEvent } from "@/lib/channels/events";

async function integration(key:string){const admin=createAdminClient();const{data,error}=await admin.from("integrations").select("id,organization_id,credentials_encrypted,external_account_id").eq("webhook_path_key",key).eq("provider","meta_whatsapp").eq("channel","whatsapp").eq("status","connected").maybeSingle();if(error||!data?.credentials_encrypted)return null;return data;}
export async function GET(req:NextRequest,{params}:{params:Promise<{integrationKey:string}>}){const{integrationKey}=await params;const item=await integration(integrationKey);if(!item)return new NextResponse("Not found",{status:404});const secret=JSON.parse(decryptSecret(item.credentials_encrypted));const mode=req.nextUrl.searchParams.get("hub.mode");const token=req.nextUrl.searchParams.get("hub.verify_token");const challenge=req.nextUrl.searchParams.get("hub.challenge");if(mode==="subscribe"&&constantTimeTokenEquals(token,secret.verifyToken)&&challenge)return new NextResponse(challenge,{status:200});return new NextResponse("Verification failed",{status:403});}
export async function POST(req:NextRequest,{params}:{params:Promise<{integrationKey:string}>}){
 const{integrationKey}=await params;const item=await integration(integrationKey);if(!item)return new NextResponse("Not found",{status:404});const admin=createAdminClient();
 const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";try{await enforceRateLimit(`wa-webhook:${integrationKey}:${ip}`,180,60);}catch{return NextResponse.json({error:"Rate limit exceeded"},{status:429});}
 const raw=await req.text();const secret=JSON.parse(decryptSecret(item.credentials_encrypted));if(!verifyMetaSignature(raw,req.headers.get("x-hub-signature-256"),secret.appSecret)){await admin.from("security_events").insert({organization_id:item.organization_id,event_type:"webhook.invalid_signature",severity:"warning",ip_address:ip,resource:"whatsapp",metadata:{integration_id:item.id}});return new NextResponse("Invalid signature",{status:401});}
 const eventKey=createHash("sha256").update(raw).digest("hex");const{error:receiptError}=await admin.from("webhook_receipts").insert({integration_id:item.id,provider:"meta_whatsapp",event_key:eventKey});if(receiptError?.code==="23505")return NextResponse.json({received:true,replay:true});if(receiptError)return NextResponse.json({error:"Webhook receipt failed"},{status:500});
 let payload:any;try{payload=JSON.parse(raw);}catch{return new NextResponse("Invalid JSON",{status:400});}
 for(const entry of payload.entry||[])for(const change of entry.changes||[]){const value=change.value||{};for(const s of value.statuses||[]){const mapped=s.status==="read"?"read":s.status==="delivered"?"delivered":s.status==="sent"?"sent":s.status==="failed"?"failed":"accepted";await recordProviderEvent({organizationId:item.organization_id,channel:"whatsapp",provider:"meta_whatsapp",providerMessageId:s.id,eventType:mapped,metadata:s,destination:s.recipient_id});}
   for(const message of value.messages||[]){const from=String(message.from||"");const contact=from?await findContactByPhone(item.organization_id,from):null;const body=message.text?.body||message.button?.text||message.interactive?.button_reply?.title||message.interactive?.list_reply?.title||null;await admin.from("inbound_messages").upsert({organization_id:item.organization_id,contact_id:contact?.id||null,channel:"whatsapp",provider:"meta_whatsapp",provider_message_id:message.id,sender:from,recipient:value.metadata?.display_phone_number||null,message_type:message.type||"unknown",body,media:message.image||message.document||message.audio?[message.image||message.document||message.audio]:[],raw_payload:message,received_at:message.timestamp?new Date(Number(message.timestamp)*1000).toISOString():new Date().toISOString()},{onConflict:"provider,provider_message_id",ignoreDuplicates:true});if(contact?.id)await admin.from("communication_history").insert({organization_id:item.organization_id,contact_id:contact.id,channel:"whatsapp",direction:"inbound",status:"received",subject:null,destination:from,provider:"meta_whatsapp",provider_message_id:message.id,metadata:{body,type:message.type}});if(contact?.id&&body&&["stop","unsubscribe","cancel","quit"].includes(String(body).trim().toLowerCase())){const normalized=from.replace(/\D/g,"");await admin.from("contacts").update({whatsapp_consent:false}).eq("id",contact.id);await admin.from("suppression_entries").upsert({organization_id:item.organization_id,contact_id:contact.id,channel:"whatsapp",destination:normalized,reason:"unsubscribe",source:"whatsapp_inbound"},{onConflict:"organization_id,channel,destination"});}await admin.from("message_events").insert({organization_id:item.organization_id,channel:"whatsapp",provider:"meta_whatsapp",provider_message_id:message.id,event_type:"received",metadata:{from,type:message.type}});}
 }
 return NextResponse.json({received:true});
}
