import { createAdminClient } from "@/lib/supabase/admin";

const recipientStatuses=new Set(["sent","accepted","delivered","opened","read","clicked","bounced","undelivered","failed","unsubscribed"]);
export async function recordProviderEvent(input:{organizationId:string;channel:"email"|"sms"|"whatsapp";provider:string;providerMessageId?:string|null;eventType:string;metadata?:Record<string,unknown>;destination?:string|null}){
 const admin=createAdminClient();let recipient:any=null;
 if(input.providerMessageId){const{data}=await admin.from("campaign_recipients").select("id,campaign_id,contact_id,destination,email,phone,whatsapp_phone").eq("organization_id",input.organizationId).eq("provider_message_id",input.providerMessageId).maybeSingle();recipient=data;}
 let automationBase:any=null;
 if(!recipient&&input.providerMessageId){const{data}=await admin.from("message_events").select("automation_id,automation_enrollment_id,automation_step_id").eq("organization_id",input.organizationId).eq("provider_message_id",input.providerMessageId).not("automation_enrollment_id","is",null).order("id",{ascending:true}).limit(1).maybeSingle();automationBase=data;}
 await admin.from("message_events").insert({organization_id:input.organizationId,campaign_id:recipient?.campaign_id||null,recipient_id:recipient?.id||null,automation_id:automationBase?.automation_id||null,automation_enrollment_id:automationBase?.automation_enrollment_id||null,automation_step_id:automationBase?.automation_step_id||null,channel:input.channel,provider:input.provider,provider_message_id:input.providerMessageId||null,event_type:input.eventType,metadata:input.metadata||{}});
 if(recipient&&recipientStatuses.has(input.eventType)){await admin.from("campaign_recipients").update({status:input.eventType}).eq("id",recipient.id);if(recipient.contact_id)await admin.from("communication_history").insert({organization_id:input.organizationId,contact_id:recipient.contact_id,campaign_id:recipient.campaign_id,recipient_id:recipient.id,channel:input.channel,direction:"outbound",status:input.eventType,destination:input.destination||recipient.destination||recipient.email||recipient.whatsapp_phone||recipient.phone,provider:input.provider,provider_message_id:input.providerMessageId,metadata:input.metadata||{}});await admin.rpc("refresh_campaign_metrics",{p_campaign_id:recipient.campaign_id});}
 if(automationBase?.automation_enrollment_id){const{data:en}=await admin.from("automation_enrollments").select("contact_id").eq("id",automationBase.automation_enrollment_id).maybeSingle();if(en?.contact_id)await admin.from("communication_history").insert({organization_id:input.organizationId,contact_id:en.contact_id,automation_id:automationBase.automation_id,automation_enrollment_id:automationBase.automation_enrollment_id,channel:input.channel,direction:"outbound",status:input.eventType,destination:input.destination||null,provider:input.provider,provider_message_id:input.providerMessageId,metadata:input.metadata||{}});}
 return recipient;
}

export async function findContactByPhone(organizationId:string,raw:string){const admin=createAdminClient();const normalized=raw.replace(/\D/g,"");const variants=Array.from(new Set([raw,normalized,`+${normalized}`]));for(const value of variants){const{data}=await admin.from("contacts").select("id").eq("organization_id",organizationId).or(`phone.eq.${value},whatsapp_phone.eq.${value}`).limit(1).maybeSingle();if(data)return data;}return null;}
