import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentContext } from "@/lib/auth/context";
import { scheduleCampaign,submitCampaign,approveCampaign,rejectCampaign } from "../actions";

export default async function CampaignDetail({params}:{params:Promise<{id:string}>}){
  const{id}=await params;const ctx=await getCurrentContext();const orgId=ctx?.membership?.organization_id as string;const supabase=await createClient();
  const campaignQ=await supabase.from("campaigns").select("*").eq("organization_id",orgId).eq("id",id).maybeSingle();if(!campaignQ.data)notFound();const c=campaignQ.data;
  const[metricsQ,integrationsQ,recipientsQ,approvalQ,canApproveQ]=await Promise.all([
    supabase.from("campaign_metrics").select("*").eq("campaign_id",id).maybeSingle(),
    supabase.from("integrations").select("provider,sender_email,daily_limit,status").eq("organization_id",orgId).eq("channel",c.channel).eq("status","connected"),
    supabase.from("campaign_recipients").select("id,status,email,phone,whatsapp_phone,destination,sent_at,last_error",{count:"exact"}).eq("campaign_id",id).limit(20),
    supabase.from("campaign_approval_events").select("id,action,note,created_at,actor_id").eq("campaign_id",id).order("created_at",{ascending:false}).limit(20),
    supabase.rpc("has_permission",{p_org:orgId,p_permission:"campaigns.approve"})
  ]);
  const m=metricsQ.data;const canApprove=Boolean(canApproveQ.data);
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="eyebrow">{String(c.channel).toUpperCase()} campaign workspace</p><div className="mt-1 flex flex-wrap items-center gap-3"><h2 className="text-3xl font-semibold">{c.name}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold capitalize">{String(c.status).replaceAll("_"," ")}</span></div><p className="mt-2 text-sm text-slate-500">{c.channel==="email"?c.subject:(c.text_content||"Provider-approved channel template")}</p>{c.rejection_reason&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">Returned for changes: {c.rejection_reason}</p>}</div>
  <div className="grid gap-4 sm:grid-cols-4">{[["Recipients",m?.recipients??c.audience_snapshot_count],["Delivered",m?.delivered??0],[c.channel==="whatsapp"?"Read":"Opened",m?.opened??0],["Clicked",m?.clicked??0]].map(([k,v])=><div key={String(k)} className="panel p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div>
  {c.status==="draft"&&<form action={submitCampaign} className="panel flex items-center justify-between gap-4 p-5"><input type="hidden" name="campaign_id" value={c.id}/><div><h3 className="font-semibold">Ready for review?</h3><p className="text-sm text-slate-500">Submit this draft to an authorized approver.</p></div><button className="btn-primary">Submit for approval</button></form>}
  {c.status==="pending_approval"&&canApprove&&<div className="panel grid gap-4 p-5 md:grid-cols-2"><form action={approveCampaign}><input type="hidden" name="campaign_id" value={c.id}/><h3 className="font-semibold">Approve campaign</h3><p className="my-3 text-sm text-slate-500">Approval unlocks scheduling and sending.</p><button className="btn-primary">Approve campaign</button></form><form action={rejectCampaign}><input type="hidden" name="campaign_id" value={c.id}/><h3 className="font-semibold">Return for changes</h3><textarea required minLength={3} name="reason" className="field my-3 min-h-20" placeholder="Explain what should be corrected"/><button className="btn-secondary">Reject / return</button></form></div>}
  {c.status==="approved"&&<form action={scheduleCampaign} className="panel grid gap-4 p-6 md:grid-cols-3"><input type="hidden" name="campaign_id" value={c.id}/><label className="space-y-2"><span className="text-sm font-semibold">{c.channel.toUpperCase()} provider</span><select required name="provider" className="field"><option value="">Select connected provider</option>{(integrationsQ.data||[]).map(i=><option key={i.provider} value={i.provider}>{i.provider} — {i.daily_limit||"no"} daily limit</option>)}</select></label><label className="space-y-2"><span className="text-sm font-semibold">Send/schedule time</span><input required name="scheduled_at" type="datetime-local" className="field"/></label><div className="flex items-end"><button className="btn-primary w-full">Queue approved campaign</button></div></form>}
  <div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div className="panel p-6"><h3 className="font-semibold">Recipient processing</h3><div className="mt-4 space-y-2">{(recipientsQ.data||[]).map(r=><div key={r.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-slate-100 py-3 text-sm"><div><p>{r.destination||r.email||r.whatsapp_phone||r.phone}</p>{r.last_error&&<p className="mt-1 text-xs text-rose-600">{r.last_error}</p>}</div><span className="text-xs font-semibold capitalize text-slate-500">{r.status}</span></div>)}{!(recipientsQ.data||[]).length&&<p className="text-sm text-slate-500">No recipients have been materialized yet.</p>}</div></div><div className="panel p-6"><h3 className="font-semibold">Approval history</h3><div className="mt-4 space-y-3">{(approvalQ.data||[]).map((a:any)=><div key={a.id} className="border-l-2 border-slate-200 pl-3"><p className="text-sm font-semibold capitalize">{a.action}</p><p className="text-xs text-slate-500">{new Date(a.created_at).toLocaleString()}</p>{a.note&&<p className="mt-1 text-xs text-slate-600">{a.note}</p>}</div>)}{!approvalQ.data?.length&&<p className="text-sm text-slate-500">No approval activity yet.</p>}</div></div></div></div>;
}
