"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
const block=z.object({id:z.string(),type:z.enum(["logo","heading","paragraph","image","button","divider","spacer","footer","social","unsubscribe"]),text:z.string().optional(),url:z.string().optional(),label:z.string().optional(),align:z.enum(["left","center","right"]).optional()});
const schema=z.object({name:z.string().min(2).max(120),category:z.string().min(1).max(60),subject:z.string().min(1).max(200),preheader:z.string().max(240).optional(),content:z.array(block).max(60)});
export async function createTemplate(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const parsed=schema.parse({name:formData.get("name"),category:formData.get("category"),subject:formData.get("subject"),preheader:String(formData.get("preheader")||""),content:JSON.parse(String(formData.get("content")||"[]"))});const supabase=await createClient();const orgId=context.membership.organization_id as string;const {data,error}=await supabase.from("email_templates").insert({organization_id:orgId,created_by:context.user.id,updated_by:context.user.id,status:"active",...parsed}).select("id").single();if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({organization_id:orgId,user_id:context.user.id,action:"template.create",entity_type:"email_template",entity_id:data.id,after_data:{name:parsed.name,category:parsed.category,subject:parsed.subject}});redirect("/templates");}
export async function archiveTemplate(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const id=z.string().uuid().parse(formData.get("id"));const supabase=await createClient();const orgId=context.membership.organization_id as string;const {error}=await supabase.from("email_templates").update({status:"archived",updated_by:context.user.id}).eq("id",id).eq("organization_id",orgId);if(error)throw new Error(error.message);redirect("/templates");}

const channelTemplateSchema=z.object({channel:z.enum(["sms","whatsapp"]),name:z.string().min(2).max(120),category:z.string().min(1).max(60),body:z.string().min(1).max(4000),provider_template_name:z.string().max(200).optional(),provider_template_language:z.string().max(20).optional(),provider_components:z.string().optional()});
export async function createChannelTemplate(formData:FormData){
 const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");
 const parsed=channelTemplateSchema.parse(Object.fromEntries(formData));const orgId=context.membership.organization_id as string;const supabase=await createClient();
 if(parsed.channel==="whatsapp"&&!parsed.provider_template_name)throw new Error("WhatsApp templates require the exact approved Meta template name.");
 let components:unknown[]=[];try{components=parsed.provider_components?JSON.parse(parsed.provider_components):[];if(!Array.isArray(components))throw new Error();}catch{throw new Error("Provider components must be a JSON array.");}
 const{error}=await supabase.from("channel_templates").insert({organization_id:orgId,channel:parsed.channel,name:parsed.name,category:parsed.category,body:parsed.body,provider_template_name:parsed.provider_template_name||null,provider_template_language:parsed.provider_template_language||null,provider_components:components,status:"active",created_by:context.user.id,updated_by:context.user.id});if(error)throw new Error(error.message);redirect("/templates");
}
export async function archiveChannelTemplate(formData:FormData){const context=await getCurrentContext();if(!context?.membership||!context.user)throw new Error("Authentication required");const id=z.string().uuid().parse(formData.get("id"));const supabase=await createClient();const orgId=context.membership.organization_id as string;const{error}=await supabase.from("channel_templates").update({status:"archived",updated_by:context.user.id}).eq("id",id).eq("organization_id",orgId);if(error)throw new Error(error.message);redirect("/templates");}
