import Link from "next/link";
import { Archive,BookOpenText,MessageSquareText,Plus } from "lucide-react";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { archiveTemplate,archiveChannelTemplate,createChannelTemplate } from "./actions";
export default async function TemplatesPage(){
 const context=await getCurrentContext();const orgId=context?.membership?.organization_id as string;const supabase=await createClient();
 const[emailQ,channelQ]=await Promise.all([supabase.from("email_templates").select("id,name,category,subject,status,content,updated_at").eq("organization_id",orgId).neq("status","archived").order("updated_at",{ascending:false}),supabase.from("channel_templates").select("id,channel,name,category,body,provider_template_name,provider_template_language,status,updated_at").eq("organization_id",orgId).neq("status","archived").order("updated_at",{ascending:false})]);
 return <div className="space-y-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Content library</p><h1 className="mt-1 text-2xl font-bold">Channel templates</h1><p className="mt-1 text-sm text-slate-500">Reusable, personalization-ready Email, SMS and WhatsApp content.</p></div><Link href="/templates/new" className="btn-primary"><Plus className="size-4"/>Create email template</Link></div>
 <section className="space-y-4"><h2 className="text-lg font-bold">Email templates</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(emailQ.data||[]).map(t=><article key={t.id} className="panel overflow-hidden"><div className="grid h-24 place-items-center border-b border-slate-100 bg-slate-50"><BookOpenText className="size-7 text-slate-300"/></div><div className="p-5"><div className="flex justify-between gap-3"><div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold uppercase">{t.category}</span><h3 className="mt-3 font-bold">{t.name}</h3></div><form action={archiveTemplate}><input type="hidden" name="id" value={t.id}/><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Archive className="size-4"/></button></form></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{t.subject}</p></div></article>)}{!emailQ.data?.length&&<div className="panel col-span-full p-8 text-center text-sm text-slate-500">No email templates yet.</div>}</div></section>
 <section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><form action={createChannelTemplate} className="panel space-y-4 p-6"><div><h2 className="font-bold">Create SMS / WhatsApp template</h2><p className="mt-1 text-sm text-slate-500">WhatsApp outbound campaigns must reference the exact approved Meta template name.</p></div><label className="block space-y-2"><span className="text-sm font-semibold">Channel</span><select name="channel" className="field"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><input required name="name" className="field" placeholder="Template display name"/><input required name="category" className="field" defaultValue="general" placeholder="Category"/><textarea required name="body" className="field min-h-32 py-3" placeholder="Hi {{first_name}}, ..."/><input name="provider_template_name" className="field" placeholder="WhatsApp approved template name (WhatsApp only)"/><input name="provider_template_language" className="field" defaultValue="en" placeholder="WhatsApp language code"/><textarea name="provider_components" className="field min-h-24 py-3 font-mono text-xs" defaultValue="[]" placeholder='Meta components JSON e.g. [{"type":"body","parameters":[]}]'/><button className="btn-primary w-full">Save channel template</button></form>
 <div className="space-y-3">{(channelQ.data||[]).map((t:any)=><article key={t.id} className="panel p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><MessageSquareText className="size-5"/></div><div><div className="flex items-center gap-2"><h3 className="font-bold">{t.name}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase">{t.channel}</span></div><p className="mt-1 line-clamp-2 text-sm text-slate-500">{t.body}</p>{t.provider_template_name&&<p className="mt-2 text-xs text-slate-400">Meta: {t.provider_template_name} · {t.provider_template_language||"en"}</p>}</div></div><form action={archiveChannelTemplate}><input type="hidden" name="id" value={t.id}/><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Archive className="size-4"/></button></form></div></article>)}{!channelQ.data?.length&&<div className="panel p-10 text-center text-sm text-slate-500">No SMS or WhatsApp templates yet.</div>}</div></section>
 </div>;
}
