"use server";
import { z } from "zod";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { resolveCampaignAudience } from "@/lib/campaigns/audience";
import { recordAudit } from "@/lib/audit";

const stepSchema=z.object({stepType:z.enum(["email","sms","whatsapp","delay","condition"]),name:z.string().max(100).optional(),waitMinutes:z.coerce.number().int().min(0).max(525600).default(0),config:z.record(z.unknown()).default({})});
const journeySchema=z.object({name:z.string().min(2).max(140),description:z.string().max(500).optional(),triggerType:z.enum(["manual","list","segment","contact_created","campaign_event"]),listId:z.string().uuid().or(z.literal("")),segmentId:z.string().uuid().or(z.literal("")),triggerEventType:z.string().max(40).optional(),steps:z.array(stepSchema).min(1).max(30)});
async function base(){const ctx=await getCurrentContext();if(!ctx?.membership||!ctx.user)throw new Error("Authentication required");const orgId=ctx.membership.organization_id as string;const supabase=await createClient();const{data:ok}=await supabase.rpc("has_permission",{p_org:orgId,p_permission:"automation.manage"});if(!ok)throw new Error("Automation management permission required.");return{ctx,orgId,supabase};}
export async function createJourney(fd:FormData){const{ctx,orgId,supabase}=await base();const steps=JSON.parse(String(fd.get("steps")||"[]"));const parsed=journeySchema.parse({name:fd.get("name"),description:String(fd.get("description")||""),triggerType:fd.get("trigger_type"),listId:String(fd.get("list_id")||""),segmentId:String(fd.get("segment_id")||""),triggerEventType:String(fd.get("trigger_event_type")||""),steps});if(parsed.triggerType==="list"&&!parsed.listId)throw new Error("Select a list for a list-triggered journey.");if(parsed.triggerType==="segment"&&!parsed.segmentId)throw new Error("Select a segment for a segment-triggered journey.");const{data:j,error}=await supabase.from("automation_journeys").insert({organization_id:orgId,name:parsed.name,description:parsed.description||null,trigger_type:parsed.triggerType,trigger_config:parsed.triggerType==="campaign_event"?{event_type:parsed.triggerEventType||"delivered"}:{},list_id:parsed.triggerType==="list"?parsed.listId:null,segment_id:parsed.triggerType==="segment"?parsed.segmentId:null,created_by:ctx.user.id,status:"draft"}).select("id").single();if(error)throw new Error(error.message);const rows=parsed.steps.map((s,i)=>({organization_id:orgId,automation_id:j.id,step_order:i+1,step_type:s.stepType,name:s.name||null,wait_minutes:s.stepType==="delay"?s.waitMinutes:0,config:s.config}));const{error:se}=await supabase.from("automation_steps").insert(rows);if(se)throw new Error(se.message);await recordAudit({organizationId:orgId,userId:ctx.user.id,action:"automation.create",entityType:"automation_journey",entityId:j.id,category:"automation",afterData:{name:parsed.name,trigger_type:parsed.triggerType,steps:rows.length}});redirect("/automation");}
export async function setJourneyStatus(fd:FormData){const{ctx,orgId,supabase}=await base();const id=z.string().uuid().parse(fd.get("id"));const status=z.enum(["active","paused","archived"]).parse(fd.get("status"));const{data:j}=await supabase.from("automation_journeys").select("*").eq("organization_id",orgId).eq("id",id).single();if(!j)throw new Error("Journey not found.");await supabase.from("automation_journeys").update({status,activated_by:status==="active"?ctx.user.id:j.activated_by,activated_at:status==="active"?new Date().toISOString():j.activated_at}).eq("id",id).eq("organization_id",orgId);
 if(status==="active"&&(j.trigger_type==="list"||j.trigger_type==="segment")){const contacts=await resolveCampaignAudience(orgId,j.trigger_type,j.list_id,j.segment_id);const{data:first}=await supabase.from("automation_steps").select("*").eq("automation_id",id).order("step_order").limit(1).maybeSingle();if(first){for(const c of contacts){const{data:existing}=await supabase.from("automation_enrollments").select("id").eq("automation_id",id).eq("contact_id",c.id).in("status",["active","completed"]).limit(1).maybeSingle();if(existing)continue;const{data:en}=await supabase.from("automation_enrollments").insert({organization_id:orgId,automation_id:id,contact_id:c.id,status:"active",current_step_order:first.step_order}).select("id").single();if(en){const when=new Date(Date.now()+Math.max(0,first.wait_minutes||0)*60000);await supabase.from("automation_step_runs").insert({organization_id:orgId,automation_id:id,enrollment_id:en.id,step_id:first.id,step_order:first.step_order,status:first.wait_minutes>0?"waiting":"pending",scheduled_for:when.toISOString()});}}}}
 await recordAudit({organizationId:orgId,userId:ctx.user.id,action:`automation.${status}`,entityType:"automation_journey",entityId:id,category:"automation",severity:status==="active"?"notice":"info"});revalidatePath("/automation");}
export async function enrollManualContact(fd:FormData){const{ctx,orgId,supabase}=await base();const automationId=z.string().uuid().parse(fd.get("id"));const email=z.string().email().parse(fd.get("email")).toLowerCase();const{data:j}=await supabase.from("automation_journeys").select("id,status,trigger_type").eq("organization_id",orgId).eq("id",automationId).single();if(!j||j.status!=="active"||j.trigger_type!=="manual")throw new Error("This journey is not an active manual journey.");const{data:contact}=await supabase.from("contacts").select("id").eq("organization_id",orgId).ilike("email",email).eq("is_active",true).maybeSingle();if(!contact)throw new Error("No active contact was found with that email.");const{data:existing}=await supabase.from("automation_enrollments").select("id").eq("automation_id",automationId).eq("contact_id",contact.id).in("status",["active","completed"]).limit(1).maybeSingle();if(existing)throw new Error("This contact is already enrolled or has completed the journey.");const{data:first}=await supabase.from("automation_steps").select("*").eq("automation_id",automationId).order("step_order").limit(1).maybeSingle();if(!first)throw new Error("Journey has no steps.");const{data:en,error}=await supabase.from("automation_enrollments").insert({organization_id:orgId,automation_id:automationId,contact_id:contact.id,status:"active",current_step_order:first.step_order}).select("id").single();if(error)throw new Error(error.message);const when=new Date(Date.now()+Math.max(0,first.wait_minutes||0)*60000);await supabase.from("automation_step_runs").insert({organization_id:orgId,automation_id:automationId,enrollment_id:en.id,step_id:first.id,step_order:first.step_order,status:first.wait_minutes>0?"waiting":"pending",scheduled_for:when.toISOString()});await recordAudit({organizationId:orgId,userId:ctx.user.id,action:"automation.manual_enroll",entityType:"automation_journey",entityId:automationId,category:"automation",afterData:{contact_id:contact.id}});revalidatePath("/automation");}
