"use server";
import { z } from "zod";
import { redirect } from "next/navigation";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { encryptSecret,decryptSecret } from "@/lib/security/secrets";
import { makeEmailProvider } from "@/lib/providers/email";
import { makeSmsProvider } from "@/lib/providers/sms";
import { makeWhatsAppProvider } from "@/lib/providers/whatsapp";
import { recordAudit } from "@/lib/audit";

async function base(){const ctx=await getCurrentContext();if(!ctx?.membership||!ctx.user)throw new Error("Authentication required");const orgId=ctx.membership.organization_id as string;const supabase=await createClient();const{data:ok}=await supabase.rpc("has_permission",{p_org:orgId,p_permission:"integrations.manage"});if(!ok)throw new Error("Integration management permission required.");return{ctx,orgId,supabase};}
const emailSchema=z.object({provider:z.enum(["brevo","resend","mailjet"]),api_key:z.string().min(8),api_secret:z.string().optional(),sender_name:z.string().min(2),sender_email:z.string().email(),reply_to:z.string().email().or(z.literal("")),daily_limit:z.coerce.number().int().min(1).max(1000000),monthly_limit:z.coerce.number().int().min(1).max(100000000)});
export async function saveIntegration(fd:FormData){const{ctx,orgId,supabase}=await base();const p=emailSchema.parse(Object.fromEntries(fd));const encrypted=encryptSecret(JSON.stringify({apiKey:p.api_key,apiSecret:p.api_secret||undefined}));const{error}=await supabase.from("integrations").upsert({organization_id:orgId,provider:p.provider,channel:"email",credentials_encrypted:encrypted,sender_name:p.sender_name,sender_email:p.sender_email,reply_to:p.reply_to||null,status:"connected",daily_limit:p.daily_limit,monthly_limit:p.monthly_limit,last_error:null},{onConflict:"organization_id,provider,channel"});if(error)throw error;await recordAudit({organizationId:orgId,userId:ctx.user.id,action:"integration.update",entityType:"integration",entityId:p.provider,category:"integration",severity:"notice",afterData:{provider:p.provider,channel:"email",sender_email:p.sender_email}});redirect("/integrations");}
const smsSchema=z.object({provider:z.enum(["termii","custom_sms"]),api_key:z.string().optional(),base_url:z.string().url().optional().or(z.literal("")),sender_id:z.string().min(2).max(20),route:z.string().optional(),endpoint:z.string().url().optional().or(z.literal("")),bearer_token:z.string().optional(),daily_limit:z.coerce.number().int().min(1).max(1000000),monthly_limit:z.coerce.number().int().min(1).max(100000000)});
export async function saveSmsIntegration(fd:FormData){const{ctx,orgId,supabase}=await base();const p=smsSchema.parse(Object.fromEntries(fd));let secret:any;if(p.provider==="termii"){if(!p.api_key||!p.base_url)throw new Error("Termii API key and regional base URL are required.");secret={apiKey:p.api_key,baseUrl:p.base_url,senderId:p.sender_id,route:p.route||"generic"};}else{if(!p.endpoint)throw new Error("Custom SMS endpoint is required.");secret={endpoint:p.endpoint,bearerToken:p.bearer_token||undefined,senderId:p.sender_id};}const{error}=await supabase.from("integrations").upsert({organization_id:orgId,provider:p.provider,channel:"sms",credentials_encrypted:encryptSecret(JSON.stringify(secret)),sender_name:p.sender_id,status:"connected",daily_limit:p.daily_limit,monthly_limit:p.monthly_limit,last_error:null,config:{route:p.route||null,base_url:p.base_url||null,endpoint:p.endpoint||null}},{onConflict:"organization_id,provider,channel"});if(error)throw error;await recordAudit({organizationId:orgId,userId:ctx.user.id,action:"integration.update",entityType:"integration",entityId:p.provider,category:"integration",severity:"notice",afterData:{provider:p.provider,channel:"sms",sender_id:p.sender_id}});redirect("/integrations");}
const waSchema=z.object({access_token:z.string().min(20),phone_number_id:z.string().min(5),graph_version:z.string().regex(/^v\d+\.\d+$/),app_secret:z.string().min(8),verify_token:z.string().min(8),daily_limit:z.coerce.number().int().min(1).max(1000000),monthly_limit:z.coerce.number().int().min(1).max(100000000)});
export async function saveWhatsAppIntegration(fd:FormData){const{ctx,orgId,supabase}=await base();const p=waSchema.parse(Object.fromEntries(fd));const encrypted=encryptSecret(JSON.stringify({accessToken:p.access_token,phoneNumberId:p.phone_number_id,graphVersion:p.graph_version,appSecret:p.app_secret,verifyToken:p.verify_token}));const{error}=await supabase.from("integrations").upsert({organization_id:orgId,provider:"meta_whatsapp",channel:"whatsapp",credentials_encrypted:encrypted,external_account_id:p.phone_number_id,status:"connected",daily_limit:p.daily_limit,monthly_limit:p.monthly_limit,last_error:null,config:{graph_version:p.graph_version}},{onConflict:"organization_id,provider,channel"});if(error)throw error;await recordAudit({organizationId:orgId,userId:ctx.user.id,action:"integration.update",entityType:"integration",entityId:"meta_whatsapp",category:"integration",severity:"notice",afterData:{provider:"meta_whatsapp",channel:"whatsapp",phone_number_id:p.phone_number_id,graph_version:p.graph_version}});redirect("/integrations");}
export async function testIntegration(fd:FormData){const{orgId,supabase}=await base();const provider=z.string().min(2).parse(fd.get("provider"));const channel=z.enum(["email","sms","whatsapp"]).parse(fd.get("channel"));const{data,error}=await supabase.from("integrations").select("credentials_encrypted").eq("organization_id",orgId).eq("provider",provider).eq("channel",channel).single();if(error||!data?.credentials_encrypted)throw new Error("Provider is not configured.");const secret=JSON.parse(decryptSecret(data.credentials_encrypted));let result:{ok:boolean;message:string};if(channel==="email")result=await makeEmailProvider(provider,secret).validateConfiguration();else if(channel==="sms")result=await makeSmsProvider(provider,secret).validateConfiguration();else result=await makeWhatsAppProvider(provider,secret).validateConfiguration();await supabase.from("integrations").update({last_tested_at:new Date().toISOString(),last_error:result.ok?null:result.message,status:result.ok?"connected":"error"}).eq("organization_id",orgId).eq("provider",provider).eq("channel",channel);redirect(`/integrations?tested=${provider}&ok=${result.ok?"1":"0"}`);}
