import { createClient } from "@/lib/supabase/server";
import { getCurrentContext } from "@/lib/auth/context";
import { saveIntegration,saveSmsIntegration,saveWhatsAppIntegration,testIntegration } from "./actions";

function Status({value}:{value?:string|null}){return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize">{value?.replaceAll("_"," ")||"not connected"}</span>}
export default async function IntegrationsPage(){
 const ctx=await getCurrentContext();const orgId=ctx?.membership?.organization_id as string;const supabase=await createClient();const{data=[]}=await supabase.from("integrations").select("id,provider,channel,status,sender_name,sender_email,reply_to,daily_limit,monthly_limit,last_tested_at,last_error,external_account_id,webhook_path_key,config").eq("organization_id",orgId);
 const appUrl=process.env.APP_URL||"";
 const emailProviders=[{key:"brevo",name:"Brevo",daily:300,monthly:9000},{key:"resend",name:"Resend",daily:100,monthly:3000},{key:"mailjet",name:"Mailjet",daily:200,monthly:6000}] as const;
 const current=(provider:string,channel:string)=>(data as any[]).find(x=>x.provider===provider&&x.channel===channel);
 return <div className="mx-auto max-w-6xl space-y-8"><div><p className="eyebrow">Channels</p><h2 className="mt-1 text-3xl font-semibold">Integrations</h2><p className="mt-2 text-sm text-slate-500">Provider secrets are encrypted server-side. Campaign logic remains provider-independent.</p></div>
 <section className="space-y-4"><div><h3 className="text-xl font-bold">Email</h3><p className="text-sm text-slate-500">Brevo, Resend or Mailjet.</p></div><div className="grid gap-5 lg:grid-cols-3">{emailProviders.map(p=>{const c=current(p.key,"email");return <div key={p.key} className="panel p-5"><div className="flex items-start justify-between"><div><h4 className="font-semibold">{p.name}</h4><p className="mt-1 text-xs text-slate-500">Default {p.daily}/day · {p.monthly}/month</p></div><Status value={c?.status}/></div>{c?.last_error&&<p className="mt-3 text-xs text-rose-600">{c.last_error}</p>}<details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Configure</summary><form action={saveIntegration} className="mt-4 space-y-3"><input type="hidden" name="provider" value={p.key}/><input required name="api_key" type="password" className="field" placeholder="API key"/>{p.key==="mailjet"&&<input name="api_secret" type="password" className="field" placeholder="API secret"/>}<input required name="sender_name" className="field" placeholder="Sender name" defaultValue={c?.sender_name||""}/><input required name="sender_email" type="email" className="field" placeholder="sender@example.com" defaultValue={c?.sender_email||""}/><input name="reply_to" type="email" className="field" placeholder="reply@example.com" defaultValue={c?.reply_to||""}/><div className="grid grid-cols-2 gap-2"><input required name="daily_limit" type="number" className="field" defaultValue={c?.daily_limit||p.daily}/><input required name="monthly_limit" type="number" className="field" defaultValue={c?.monthly_limit||p.monthly}/></div><button className="btn-primary w-full">Save email connection</button></form></details>{c&&<form action={testIntegration} className="mt-3"><input type="hidden" name="provider" value={p.key}/><input type="hidden" name="channel" value="email"/><button className="btn-secondary w-full">Test connection</button></form>}</div>})}</div></section>
 <section className="space-y-4"><div><h3 className="text-xl font-bold">SMS</h3><p className="text-sm text-slate-500">Termii is included for Nigerian/regional messaging; a generic HTTP SMS adapter is also available.</p></div><div className="grid gap-5 lg:grid-cols-2">
 {(["termii","custom_sms"] as const).map(provider=>{const c=current(provider,"sms");return <div key={provider} className="panel p-5"><div className="flex justify-between"><div><h4 className="font-semibold">{provider==="termii"?"Termii":"Custom SMS HTTP"}</h4><p className="mt-1 text-xs text-slate-500">{provider==="termii"?"Regional base URL + API key + sender ID":"POST JSON to your provider endpoint"}</p></div><Status value={c?.status}/></div><form action={saveSmsIntegration} className="mt-4 space-y-3"><input type="hidden" name="provider" value={provider}/>{provider==="termii"?<><input required name="api_key" type="password" className="field" placeholder="Termii API key"/><input required name="base_url" type="url" className="field" placeholder="Regional base URL from Termii dashboard"/><input name="route" className="field" placeholder="Route/channel e.g. generic" defaultValue="generic"/></>:<><input required name="endpoint" type="url" className="field" placeholder="https://provider.example/send"/><input name="bearer_token" type="password" className="field" placeholder="Bearer token (optional)"/></>}<input required name="sender_id" className="field" placeholder="Sender ID" defaultValue={c?.sender_name||""}/><div className="grid grid-cols-2 gap-2"><input required name="daily_limit" type="number" className="field" defaultValue={c?.daily_limit||1000}/><input required name="monthly_limit" type="number" className="field" defaultValue={c?.monthly_limit||30000}/></div><button className="btn-primary w-full">Save SMS connection</button></form>{c?.webhook_path_key&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><p className="font-semibold">Delivery callback URL</p><p className="mt-1 break-all">{appUrl}/api/webhooks/sms/{provider}/{c.webhook_path_key}?secret=YOUR_WEBHOOK_SECRET</p></div>}{c&&<form action={testIntegration} className="mt-3"><input type="hidden" name="provider" value={provider}/><input type="hidden" name="channel" value="sms"/><button className="btn-secondary w-full">Test connection</button></form>}</div>})}
 </div></section>
 <section className="space-y-4"><div><h3 className="text-xl font-bold">WhatsApp</h3><p className="text-sm text-slate-500">Meta WhatsApp Cloud API using approved message templates for outbound campaigns.</p></div>{(()=>{const c=current("meta_whatsapp","whatsapp");return <div className="panel max-w-3xl p-5"><div className="flex justify-between"><div><h4 className="font-semibold">Meta WhatsApp Cloud API</h4><p className="mt-1 text-xs text-slate-500">Phone Number ID {c?.external_account_id||"not configured"}</p></div><Status value={c?.status}/></div><form action={saveWhatsAppIntegration} className="mt-5 grid gap-3 md:grid-cols-2"><input required name="access_token" type="password" className="field md:col-span-2" placeholder="Permanent/system-user access token"/><input required name="phone_number_id" className="field" placeholder="Phone Number ID" defaultValue={c?.external_account_id||""}/><input required name="graph_version" className="field" placeholder="vXX.X" defaultValue={(c?.config as any)?.graph_version||""}/><input required name="app_secret" type="password" className="field" placeholder="Meta app secret"/><input required name="verify_token" type="password" className="field" placeholder="Choose webhook verify token"/><input required name="daily_limit" type="number" className="field" defaultValue={c?.daily_limit||1000}/><input required name="monthly_limit" type="number" className="field" defaultValue={c?.monthly_limit||30000}/><button className="btn-primary md:col-span-2">Save WhatsApp connection</button></form>{c?.webhook_path_key&&<div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><p className="font-semibold">Webhook URL</p><p className="mt-1 break-all">{appUrl}/api/webhooks/whatsapp/meta/{c.webhook_path_key}</p></div>}{c&&<form action={testIntegration} className="mt-3"><input type="hidden" name="provider" value="meta_whatsapp"/><input type="hidden" name="channel" value="whatsapp"/><button className="btn-secondary w-full">Test Cloud API connection</button></form>}</div>})()}</section>
 </div>;
}
