import { createAdminClient } from "@/lib/supabase/admin";
import { decryptSecret } from "@/lib/security/secrets";
import { makeEmailProvider } from "@/lib/providers/email";
import { makeSmsProvider } from "@/lib/providers/sms";
import { makeWhatsAppProvider } from "@/lib/providers/whatsapp";
import { personalize } from "@/lib/templates/personalize";
import { renderCampaignHtml } from "@/lib/campaigns/render";

function masked(value?:string|null){if(!value)return"";return `${"*".repeat(Math.max(4,value.length-4))}${value.slice(-4)}`;}
function destination(contact:any,channel:string){if(channel==="email")return contact.email?String(contact.email).trim().toLowerCase():null;const raw=channel==="sms"?contact.phone:(contact.whatsapp_phone||contact.phone);return raw?String(raw).replace(/\D/g,""):null;}
function consent(contact:any,channel:string){return channel==="email"?contact.email_consent===true:channel==="sms"?contact.sms_consent===true:contact.whatsapp_consent===true;}
function deepPersonalize(value:unknown,vars:Record<string,string>):unknown{if(typeof value==="string")return personalize(value,vars);if(Array.isArray(value))return value.map(v=>deepPersonalize(v,vars));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,deepPersonalize(v,vars)]));return value;}

async function scheduleStep(enrollment:any,automationId:string,organizationId:string,targetOrder:number){const admin=createAdminClient();const{data:step}=await admin.from("automation_steps").select("*").eq("automation_id",automationId).eq("step_order",targetOrder).maybeSingle();if(!step){await admin.from("automation_enrollments").update({status:"completed",completed_at:new Date().toISOString(),current_step_order:targetOrder}).eq("id",enrollment.id);return false;}const when=new Date(Date.now()+Math.max(0,step.wait_minutes||0)*60000);await admin.from("automation_enrollments").update({current_step_order:targetOrder}).eq("id",enrollment.id);await admin.from("automation_step_runs").upsert({organization_id:organizationId,automation_id:automationId,enrollment_id:enrollment.id,step_id:step.id,step_order:step.step_order,status:step.wait_minutes>0?"waiting":"pending",scheduled_for:when.toISOString()},{onConflict:"enrollment_id,step_id"});return true;}

export async function processAutomationRun(runId:string){
 const admin=createAdminClient();const{data:run,error}=await admin.from("automation_step_runs").select("*").eq("id",runId).single();if(error||!run)throw error||new Error("Automation run not found.");
 const[{data:journey},{data:enrollment},{data:step}]=await Promise.all([admin.from("automation_journeys").select("*").eq("id",run.automation_id).single(),admin.from("automation_enrollments").select("*").eq("id",run.enrollment_id).single(),admin.from("automation_steps").select("*").eq("id",run.step_id).single()]);
 if(!journey||!enrollment||!step)throw new Error("Automation context is incomplete.");if(journey.status!=="active"||enrollment.status!=="active"){await admin.from("automation_step_runs").update({status:"skipped",completed_at:new Date().toISOString(),result:{reason:"journey_or_enrollment_inactive"}}).eq("id",run.id);return{skipped:true};}
 const{data:contact}=await admin.from("contacts").select("*").eq("id",enrollment.contact_id).single();if(!contact)throw new Error("Automation contact not found.");
 const vars:Record<string,string>={first_name:contact.first_name||"",last_name:contact.last_name||"",full_name:contact.full_name||[contact.first_name,contact.last_name].filter(Boolean).join(" "),email:contact.email||"",phone:contact.phone||"",branch:contact.branch||"",account_type:contact.account_type||"",masked_account_number:masked(contact.account_number)};
 try{
  if(step.step_type==="delay"){await admin.from("automation_step_runs").update({status:"completed",completed_at:new Date().toISOString(),result:{delay_minutes:step.wait_minutes}}).eq("id",run.id);await scheduleStep(enrollment,journey.id,journey.organization_id,step.step_order+1);return{completed:true,type:"delay"};}
  if(step.step_type==="condition"){
   const config=step.config||{};const eventType=String(config.eventType||"opened");const lookback=Math.max(1,Number(config.lookbackMinutes||10080));const since=new Date(Date.now()-lookback*60000).toISOString();const{count}=await admin.from("message_events").select("id",{count:"exact",head:true}).eq("organization_id",journey.organization_id).eq("automation_enrollment_id",enrollment.id).eq("event_type",eventType).gte("event_timestamp",since);const matched=(count||0)>0;const target=Number(matched?config.trueStepOrder:config.falseStepOrder)||step.step_order+1;await admin.from("automation_step_runs").update({status:"completed",completed_at:new Date().toISOString(),result:{condition:eventType,matched,target}}).eq("id",run.id);await scheduleStep(enrollment,journey.id,journey.organization_id,target);return{completed:true,type:"condition",matched};
  }
  const channel=step.step_type as "email"|"sms"|"whatsapp";const to=destination(contact,channel);if(!to)throw new Error(`Contact has no ${channel} destination.`);if(!consent(contact,channel))throw new Error(`${channel} consent is not active.`);const{data:suppressed}=await admin.from("suppression_entries").select("id").eq("organization_id",journey.organization_id).eq("channel",channel).ilike("destination",String(to)).limit(1).maybeSingle();if(suppressed)throw new Error("Destination is suppressed.");
  const{data:integration}=await admin.from("integrations").select("*").eq("organization_id",journey.organization_id).eq("channel",channel).eq("status","connected").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!integration?.credentials_encrypted)throw new Error(`No connected ${channel} provider.`);const secret=JSON.parse(decryptSecret(integration.credentials_encrypted));const cfg=step.config||{};let providerMessageId="";
  if(channel==="email"){
   const{data:template}=await admin.from("email_templates").select("subject,content").eq("organization_id",journey.organization_id).eq("id",cfg.templateId).single();if(!template)throw new Error("Automation email template not found.");const sent=await makeEmailProvider(integration.provider,secret).sendEmail({to:String(to),subject:personalize(cfg.subject||template.subject,vars),html:renderCampaignHtml((template.content||[])as any[],vars),fromName:integration.sender_name||"Campaign",fromEmail:integration.sender_email,replyTo:integration.reply_to});providerMessageId=sent.providerMessageId;
  }else if(channel==="sms"){
   const{data:template}=await admin.from("channel_templates").select("body").eq("organization_id",journey.organization_id).eq("id",cfg.templateId).eq("channel","sms").single();if(!template)throw new Error("Automation SMS template not found.");const sent=await makeSmsProvider(integration.provider,secret).sendSms({to:String(to),body:personalize(template.body,vars),senderId:integration.sender_name||secret.senderId||"Campaign"});providerMessageId=sent.providerMessageId;
  }else{
   const{data:template}=await admin.from("channel_templates").select("provider_template_name,provider_template_language,provider_components").eq("organization_id",journey.organization_id).eq("id",cfg.templateId).eq("channel","whatsapp").single();if(!template?.provider_template_name)throw new Error("Automation WhatsApp template is not configured with an approved provider template.");const sent=await makeWhatsAppProvider(integration.provider,secret).sendTemplate({to:String(to),templateName:template.provider_template_name,language:template.provider_template_language||"en",components:deepPersonalize(template.provider_components||[],vars) as unknown[]});providerMessageId=sent.providerMessageId;
  }
  await admin.from("message_events").insert({organization_id:journey.organization_id,automation_id:journey.id,automation_enrollment_id:enrollment.id,automation_step_id:step.id,channel,provider:integration.provider,provider_message_id:providerMessageId,event_type:"sent",metadata:{automation:journey.name,destination:String(to),contact_id:contact.id}});
  await admin.from("communication_history").insert({organization_id:journey.organization_id,contact_id:contact.id,automation_id:journey.id,automation_enrollment_id:enrollment.id,channel,direction:"outbound",status:"sent",subject:journey.name,destination:String(to),provider:integration.provider,provider_message_id:providerMessageId,metadata:{step_order:step.step_order}});
  await admin.from("automation_step_runs").update({status:"completed",completed_at:new Date().toISOString(),provider_message_id:providerMessageId,result:{channel,provider:integration.provider}}).eq("id",run.id);await scheduleStep(enrollment,journey.id,journey.organization_id,step.step_order+1);return{completed:true,type:channel};
 }catch(error){const message=error instanceof Error?error.message:"Automation step failed";const retry=run.attempts<3;await admin.from("automation_step_runs").update({status:retry?"waiting":"failed",scheduled_for:retry?new Date(Date.now()+Math.min(60,5*run.attempts)*60000).toISOString():run.scheduled_for,last_error:message,completed_at:retry?null:new Date().toISOString()}).eq("id",run.id);if(!retry)await admin.from("automation_enrollments").update({status:"failed",last_error:message}).eq("id",enrollment.id);return{completed:false,error:message,retry};}
}

export async function enrollTriggeredAutomations(){
 const admin=createAdminClient();const{data:journeys}=await admin.from("automation_journeys").select("*").eq("status","active").in("trigger_type",["contact_created","campaign_event"]);let enrolled=0;
 for(const j of journeys||[]){
  let candidates:{contactId:string;eventId?:number}[]=[];
  if(j.trigger_type==="contact_created"){const{data}=await admin.from("contacts").select("id").eq("organization_id",j.organization_id).gte("created_at",j.activated_at||j.created_at).limit(200);candidates=(data||[]).map((x:any)=>({contactId:x.id}));}
  else{const eventType=String(j.trigger_config?.event_type||"delivered");let q=admin.from("message_events").select("id,recipient_id,campaign_id").eq("organization_id",j.organization_id).eq("event_type",eventType).gte("event_timestamp",j.activated_at||j.created_at).order("id",{ascending:false}).limit(200);if(j.trigger_config?.campaign_id)q=q.eq("campaign_id",j.trigger_config.campaign_id);const{data}=await q;for(const e of data||[]){if(!e.recipient_id)continue;const{data:r}=await admin.from("campaign_recipients").select("contact_id").eq("id",e.recipient_id).maybeSingle();if(r?.contact_id)candidates.push({contactId:r.contact_id,eventId:e.id});}}
  const{data:first}=await admin.from("automation_steps").select("*").eq("automation_id",j.id).order("step_order").limit(1).maybeSingle();if(!first)continue;
  for(const c of candidates){const{data:existing}=await admin.from("automation_enrollments").select("id").eq("automation_id",j.id).eq("contact_id",c.contactId).in("status",["active","completed"]).limit(1).maybeSingle();if(existing)continue;const{data:en}=await admin.from("automation_enrollments").insert({organization_id:j.organization_id,automation_id:j.id,contact_id:c.contactId,status:"active",current_step_order:first.step_order,trigger_event_id:c.eventId||null}).select("id").single();if(en){const when=new Date(Date.now()+Math.max(0,first.wait_minutes||0)*60000);await admin.from("automation_step_runs").insert({organization_id:j.organization_id,automation_id:j.id,enrollment_id:en.id,step_id:first.id,step_order:first.step_order,status:first.wait_minutes>0?"waiting":"pending",scheduled_for:when.toISOString()});enrolled++;}}
 }
 return enrolled;
}
