import { ContactSubnav } from "@/components/contacts/contact-subnav";
import { getCurrentContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { createCustomField } from "./actions";

export default async function ContactSettingsPage(){
  const context=await getCurrentContext(); const orgId=context?.membership?.organization_id as string; const supabase=await createClient();
  const [{data:fields},{data:mappings}]=await Promise.all([supabase.from("custom_field_definitions").select("id,name,key,type,required,options").eq("organization_id",orgId).order("created_at"),supabase.from("import_mapping_profiles").select("id,name,description,mapping,updated_at").eq("organization_id",orgId).order("updated_at",{ascending:false})]);
  return <div className="space-y-6"><div><p className="eyebrow">Contacts</p><h1 className="mt-1 text-2xl font-bold">Fields & mappings</h1><p className="mt-1 text-sm text-slate-500">Extend your contact model and reuse recurring spreadsheet formats.</p></div><ContactSubnav/><div className="grid gap-6 xl:grid-cols-2"><section className="panel overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">Custom contact fields</h2></div><form action={createCustomField} className="grid gap-3 border-b border-slate-200 bg-slate-50/60 p-5 sm:grid-cols-2"><input name="name" required className="field" placeholder="Field name"/><select name="type" className="field"><option value="text">Text</option><option value="number">Number</option><option value="date">Date</option><option value="boolean">Yes / No</option><option value="select">Select</option><option value="multi-select">Multi-select</option></select><input name="options" className="field sm:col-span-2" placeholder="Options for select fields, comma separated"/><label className="flex items-center gap-2 text-sm"><input name="required" type="checkbox"/>Required field</label><button className="btn-primary sm:justify-self-end">Add field</button></form><div className="divide-y divide-slate-100">{(fields||[]).map(f=><div key={f.id} className="flex items-center justify-between p-4"><div><div className="font-semibold">{f.name}</div><div className="text-xs text-slate-500">{f.key} · {f.type}</div></div>{f.required&&<span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700">Required</span>}</div>)}{!fields?.length&&<div className="p-8 text-center text-sm text-slate-500">No custom fields yet.</div>}</div></section><section className="panel overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">Saved import mappings</h2><p className="mt-1 text-sm text-slate-500">Mappings saved from the import workflow appear here.</p></div><div className="divide-y divide-slate-100">{(mappings||[]).map(m=><div key={m.id} className="p-5"><div className="flex items-center justify-between"><div className="font-semibold">{m.name}</div><span className="text-xs text-slate-400">{new Date(m.updated_at).toLocaleDateString()}</span></div><div className="mt-1 text-sm text-slate-500">{m.description || `${Object.keys(m.mapping as object).length} mapped columns`}</div></div>)}{!mappings?.length&&<div className="p-8 text-center text-sm text-slate-500">Save a mapping while importing a spreadsheet to reuse it here.</div>}</div></section></div></div>;
}
