"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
export function MfaManager(){const supabase=createClient();const[loading,setLoading]=useState(true);const[factorId,setFactorId]=useState("");const[qr,setQr]=useState("");const[secret,setSecret]=useState("");const[code,setCode]=useState("");const[message,setMessage]=useState("");
 async function load(){setLoading(true);const{data}=await supabase.auth.mfa.listFactors();const verified=data?.totp?.find((f:any)=>f.status==="verified");if(verified){setFactorId(verified.id);setMessage("Authenticator already enrolled. Enter a fresh code to upgrade this session.");}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function enroll(){setMessage("");const{data,error}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:"CampaignOS Authenticator"});if(error){setMessage(error.message);return}setFactorId(data.id);setQr(data.totp.qr_code);setSecret(data.totp.secret);setMessage("Scan the QR code, then verify with the 6-digit code.");}
 async function verify(){if(!factorId||code.length<6)return;setMessage("");const{data:challenge,error:ce}=await supabase.auth.mfa.challenge({factorId});if(ce){setMessage(ce.message);return}const{error}=await supabase.auth.mfa.verify({factorId,challengeId:challenge.id,code});if(error){setMessage(error.message);return}window.location.href="/dashboard";}
 if(loading)return <p className="text-sm text-slate-500">Checking authenticator status…</p>;
 return <div className="space-y-5">{!factorId&&<button onClick={enroll} className="btn-primary">Set up authenticator</button>}{qr&&<div className="space-y-3 rounded-2xl border border-slate-200 p-4"><img src={qr} alt="Authenticator QR code" className="mx-auto size-52"/><p className="text-xs text-slate-500">Manual secret: <span className="font-mono text-slate-800">{secret}</span></p></div>}{factorId&&<div className="flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,8))} inputMode="numeric" className="field" placeholder="6-digit authenticator code"/><button onClick={verify} className="btn-primary">Verify session</button></div>}{message&&<p className="text-sm text-slate-600">{message}</p>}</div>}
